## Title : Grading assignments Bingo card
## Author : Erik Bolch
c(
  "graded the best student first",
  "no name on paper",
  "handwriting is intentionally unreadable",
  "assignment submitted incorrectly",
  "apology for how bad an answer is",
  "clearly has no idea what the question was asking",
  "did not follow instructions",
  "answered all questions correctly and concisely",
  "asked for extension",
  "Peony",
  "Daisy",
  "Alstromeria",
  "Lavender",
  "Hibiscus",
  "Birds of Paradise",
  "Moonflower",
  "Pansy",
  "Hyacinth",
  "Petunia",
  "Poppy",
  "Snapdragon",
  "Violet",
  "Cosmos",
  "Calendula",
  "Azalea",
  "Begonia"
)