## Title : Assignment Grading Bingo card
## Author : Erik Bolch
c(
  "intentionally graded the best student first",
  "no name on paper/submission",
  "handwriting is intentionally illegible",
  "assignment submitted incorrectly",
  "apology included for how bad an answer is",
  "clearly has no idea what the question was asking",
  "did not follow instructions",
  "answered all questions correctly and concisely",
  "asked for extension",
  "did not submit assignment",
  "answer is not correct, but also not incorrect",
  "did not use complete sentences",
  "extremely long answer that's only slightly relevant",
  "clearly did minimal work, but meets requirements of rubric",
  "clearly spent hours working, but did not meet requiements of rubric",
  "well thought out answer",
  "answer contradicts itself",
  "submitted only for partial credit",
  "graded worst submission first",
  "answered question using only knownledge from outside the course",
  "answer looks like its from the solutions manual",
  "student has mastered getting partial credit...",
  "illustration included for clarity",
  "illustration included for ???",
  "learned something from student",
  "unending spelling errors"
)